image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
  - port: 3001
    onOpen: open-preview
    visibility: public
  - port: 5432
    onOpen: ignore
tasks:
  - init: |
      touch .env &&
      pipenv install &&
      psql -U gitpod -c 'CREATE DATABASE "4geeks";' &&
      psql -U gitpod -c 'CREATE EXTENSION unaccent;' -d 4geeks

      psql -c "ALTER USER gitpod PASSWORD 'postgres';" &&
      bash database.sh &&
      python docs/assets/greeting.py back
  - command: |
      echo "export FLASK_DEBUG=1" >> ~/.bashrc
      source ~/.bashrc
      cat .env.4geeks >> .env &&
      echo BACKEND_URL=$(gp url 3001) >> .env && 
      npm install &&
      python docs/assets/greeting.py front
    openMode: split-right

vscode:
  extensions:
    - esbenp.prettier-vscode
